### ISSUE TITLE
No webhooks

### ISSUE THREAD

**Issue by brownelvis** [akulsharma1/PublicShopifyMonitor#2]
When the monitor picks up a product and says it is sending a webhook, nothing happens.  I have tested the discord webhook url elsewhere and it works fine.

**Comment by akulsharma1** [comment]
Hello!

What website are you attempting to run the monitor on so I can debug the issue? 

Also, make sure that when inputting the website URL into the script, the URL must be exactly in the format https://kith.com/. For example, https://kith.com will not work.

**Comment by brownelvis** [comment]
Hey! I am just test running with kith at the moment, and i put it in the URL as https://kith.com/

The product monitor itself seems to work and picks up new products, the log says it picks up new product and is sending a webhook, but then the webhook doesn't appear in discord.  I pasted in the discord webhook URL exactly as it is from discord using the "Copy webhook URL" button so im not sure why its not coming through.

Thanks for the quick reply btw!

**Comment by akulsharma1** [comment]
Should work, try now.

You'll need to redownload the script.

**Comment by brownelvis** [comment]
that fixed it, thanks!
